In [1]:
import os
os.chdir('python_basics')

## map, filter, reduce

In [7]:
from functools import reduce
import numpy as np

def mul_(x,y):
    return x * y

l1 = np.random.randint(1,10,10)
l1

array([4, 7, 7, 5, 8, 6, 4, 2, 3, 9])

In [8]:
list(map(lambda x: x ** 2, l1))
list(filter(lambda x: x % 2 == 0, l1))
reduce(mul_, l1)

[16, 49, 49, 25, 64, 36, 16, 4, 9, 81]

[4, 8, 6, 4, 2]

10160640

## kwargs

In [ ]:
def print_all(*args, **kwargs):
    print(args)
    print(kwargs)

print_all(*l1,l1, a=1, b=2, c=3, d=4, e=5, f=6, g=7, h=8, i=9, j=10)

(4, 7, 7, 5, 8, 6, 4, 2, 3, 9, array([4, 7, 7, 5, 8, 6, 4, 2, 3, 9]))
{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6, 'g': 7, 'h': 8, 'i': 9, 'j': 10}


In [14]:
def print_dic(**kwargs):
    for k,v in kwargs.items():
        print(f'{k} : {v}')
print_dic(a=1, b=2, c=3, d=4, e=5, f=6, g=7, h=8, i=9, j=10)

a : 1
b : 2
c : 3
d : 4
e : 5
f : 6
g : 7
h : 8
i : 9
j : 10


## Lambda

In [15]:
sqr = lambda x : x ** 2

sqr(5)

25

In [17]:
l2 = np.random.randint(1,10,10)
l2
list(filter(lambda x : x % 2 == 0, l2))
list(map(sqr, l2))

array([5, 6, 2, 3, 6, 3, 8, 9, 6, 2])

[6, 2, 6, 8, 6, 2]

[25, 36, 4, 9, 36, 9, 64, 81, 36, 4]

In [18]:
reduce(lambda x,y : x  + y , l2)

50

In [21]:
# sum of digits 
n = 18418
reduce(lambda x ,y : int(x) + int(y)  , str(n)) , sum(map(int, str(n)))

(22, 22)

# NUMPY

In [2]:
import numpy as np

a1= np.array([1,2,3,4,5,6,7,8,9,10])
a2 = np.arange(1,11)
a1,a2

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [3]:
a1 is a2 , a1 == a2, all(a1 == a2)

(False,
 array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]),
 True)

In [4]:
populations_txt = f'./data/populations.txt'
populations_data = np.loadtxt(populations_txt, delimiter='\t').astype(int)
populations_data

array([[ 1900, 30000,  4000, 48300],
       [ 1901, 47200,  6100, 48200],
       [ 1902, 70200,  9800, 41500],
       [ 1903, 77400, 35200, 38200],
       [ 1904, 36300, 59400, 40600],
       [ 1905, 20600, 41700, 39800],
       [ 1906, 18100, 19000, 38600],
       [ 1907, 21400, 13000, 42300],
       [ 1908, 22000,  8300, 44500],
       [ 1909, 25400,  9100, 42100],
       [ 1910, 27100,  7400, 46000],
       [ 1911, 40300,  8000, 46800],
       [ 1912, 57000, 12300, 43800],
       [ 1913, 76600, 19500, 40900],
       [ 1914, 52300, 45700, 39400],
       [ 1915, 19500, 51100, 39000],
       [ 1916, 11200, 29700, 36700],
       [ 1917,  7600, 15800, 41800],
       [ 1918, 14600,  9700, 43300],
       [ 1919, 16200, 10100, 41300],
       [ 1920, 24700,  8600, 47300]])